# Generated by Django 2.1.8 on 2020-09-21 11:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0045_auto_20200921_1709'),
        ('Brands', '0012_company_plan_name'),
        ('backgroundjobs', '0002_backgroundjobs_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Report')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Company', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Brands.Company', verbose_name='Company')),
                ('outlet', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'backgroundjobs',
                'verbose_name_plural': '  backgroundjobs',
            },
        ),
    ]
