# Generated by Django 2.1.8 on 2020-08-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_statemaster_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statemaster',
            options={'ordering': ['state'], 'verbose_name': '  State/Prefecture', 'verbose_name_plural': '  State/Prefecture'},
        ),
    ]
