# Generated by Django 2.1.8 on 2021-06-14 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0032_mergebrand'),
        ('Location', '0037_areamaster_company'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='areamaster',
        #     name='company',
        #     field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='area_Company', to='Brands.Company', verbose_name='Company'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='countrymaster',
            name='currency',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_master_currency', to='Configuration.CurrencyMaster', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='isd',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)], verbose_name='ISD/Country Code'),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='iso',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='ISO'),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='mobile_no_digits',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(5)], verbose_name='Countries Mobile Number digit'),
        ),
    ]
