# Generated by Django 2.1.8 on 2021-06-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0039_auto_20210614_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymaster',
            name='isd',
            field=models.CharField(blank=True, max_length=104, null=True, verbose_name='ISD/Country Code'),
        ),
    ]
