# Generated by Django 2.1.8 on 2020-07-24 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_statemaster_short_name'),
        ('Brands', '0009_auto_20200720_1327'),
        ('Configuration', '0015_headerfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, verbose_name='Symbol')),
                ('payment_logo', models.ImageField(blank=True, null=True, upload_to='payment_logo', verbose_name='payment Logo')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('keyid', models.CharField(blank=True, max_length=50, null=True, verbose_name='keyId')),
                ('keySecret', models.CharField(blank=True, max_length=50, null=True, verbose_name='keySecret')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethod_Company', to='Brands.Company', verbose_name='Company')),
                ('country', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethod_country', to='Location.CountryMaster', verbose_name='Country')),
            ],
            options={
                'verbose_name': '   Payment Method',
                'verbose_name_plural': '   Payment Method',
            },
        ),
    ]
