# Generated by Django 2.1.8 on 2020-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0016_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit Name')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
            ],
            options={
                'verbose_name': '    Unit',
                'verbose_name_plural': '    Unit',
            },
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='active_status',
            field=models.BooleanField(default=0, verbose_name='Is Active'),
        ),
    ]
