# Generated by Django 2.1.8 on 2020-08-10 07:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0017_auto_20200725_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_deatils',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
