# Generated by Django 2.1.8 on 2020-08-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0018_unit_unit_deatils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit_deatils',
            new_name='unit_details',
        ),
    ]
