# Generated by Django 2.1.8 on 2020-08-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0010_company_is_payment'),
        ('Configuration', '0019_auto_20200810_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Name')),
                ('tax_percent', models.FloatField(blank=True, null=True, verbose_name='Percentage')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Tax_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '   Tax',
                'verbose_name_plural': '   Tax',
            },
        ),
    ]
