# Generated by Django 2.1.8 on 2020-08-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0020_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='word_limit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Character Limit'),
        ),
    ]
