# Generated by Django 2.1.8 on 2020-08-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0011_auto_20200817_1818'),
        ('Configuration', '0021_paymentmethod_word_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Source Name')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OrderSource_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '   OrderSource',
                'verbose_name_plural': '   OrderSource',
            },
        ),
    ]
