# Generated by Django 2.1.8 on 2020-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0022_ordersource'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='source', verbose_name='image'),
        ),
    ]
