# Generated by Django 2.1.8 on 2020-08-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0012_company_plan_name'),
        ('Configuration', '0024_excelimport_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Unit_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
