# Generated by Django 2.1.8 on 2020-09-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0025_unit_company'),
        ('Configuration', '0022_paymentstatus'),
    ]

    operations = [
    ]
