# Generated by Django 2.1.8 on 2020-09-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0027_dailysaledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysaledata',
            name='company',
        ),
        migrations.DeleteModel(
            name='DailySaledata',
        ),
    ]
