# Generated by Django 2.1.8 on 2020-10-07 06:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0028_auto_20200910_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverysetting',
            name='CGST',
        ),
        migrations.RemoveField(
            model_name='deliverysetting',
            name='tax_percent',
        ),
        migrations.AddField(
            model_name='deliverysetting',
            name='is_tax',
            field=models.BooleanField(default=1, verbose_name='Is Tax'),
        ),
        migrations.AddField(
            model_name='deliverysetting',
            name='price_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Price Type'),
        ),
        migrations.AddField(
            model_name='deliverysetting',
            name='tax',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Tax'),
        ),
    ]
