# Generated by Django 2.1.8 on 2020-10-08 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0030_productweightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweightage',
            name='product_schema',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Nutritional Information'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='product_subcategory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Product Subcategory'),
        ),
    ]
