# Generated by Django 2.1.8 on 2020-10-08 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0012_company_plan_name'),
        ('Configuration', '0031_auto_20201008_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweightage',
            name='addpn_grp_association',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Addon Group Association'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='allergen_Information',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Allergen Information'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Compare at price'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='food_type',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Food Type'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='included_platform',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Included PlatForm'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='is_recommended',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='kot_desc',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Kot Description'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='outlet_map',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='primaryIngredient_deatils',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='PrimaryIngredient Details'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='product_category',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='product_code',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='product_desc',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='product_image',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='product_name',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='product_schema',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Nutritional Information'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='pvideo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Product Video'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='spice',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Spice'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='tags',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='tax_association',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='variant',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='productweightage',
            name='variant_deatils',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Variant Details'),
        ),
        migrations.AlterUniqueTogether(
            name='productweightage',
            unique_together={('company',)},
        ),
    ]
