# Generated by Django 2.1.8 on 2020-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0033_websitestatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name'),
        ),
    ]
