# Generated by Django 2.1.8 on 2020-11-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0034_unit_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersource',
            name='independent_status',
            field=models.BooleanField(default=1, verbose_name='Is Status'),
        ),
    ]
