# Generated by Django 2.1.8 on 2020-11-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0035_ordersource_independent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersource',
            name='independent_status',
        ),
        migrations.AddField(
            model_name='ordersource',
            name='is_edit',
            field=models.BooleanField(default=0, verbose_name='Is Status'),
        ),
    ]
