# Generated by Django 2.1.8 on 2020-11-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0036_auto_20201109_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersource',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrderSource_source', to='independent.Source'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_source', to='independent.Independent_Unit'),
        ),
    ]
