# Generated by Django 2.1.8 on 2020-11-09 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0037_auto_20201109_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersource',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrderSource_source', to='independent.Source'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_unit', to='independent.Independent_Unit'),
        ),
    ]
