# Generated by Django 2.1.8 on 2020-11-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0039_ordersource_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_tax', to='independent.Independent_Tax'),
        ),
    ]
