# Generated by Django 2.1.8 on 2020-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0040_tax_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysetting',
            name='delivery_charge',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Delivery Charge'),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='package_charge',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Package Charge'),
        ),
    ]
