# Generated by Django 2.1.8 on 2020-12-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0042_auto_20201205_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsetting',
            name='company',
            field=models.OneToOneField(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ColorSetting_Company', to='Brands.Company', verbose_name='Company'),
        ),
    ]
