# Generated by Django 2.1.8 on 2020-12-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0044_attendanceconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceconfig',
            options={'verbose_name': '   AttendanceConfig', 'verbose_name_plural': '   AttendanceConfig'},
        ),
        migrations.AlterField(
            model_name='attendanceconfig',
            name='fullday',
            field=models.TimeField(verbose_name='Full Day'),
        ),
        migrations.AlterField(
            model_name='attendanceconfig',
            name='halfday',
            field=models.TimeField(verbose_name='Half Day'),
        ),
    ]
