# Generated by Django 2.1.8 on 2020-12-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0045_auto_20201216_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailtime', models.TimeField(verbose_name='Full Day')),
            ],
            options={
                'verbose_name': '   MailTime',
                'verbose_name_plural': '   MailTime',
            },
        ),
    ]
