# Generated by Django 2.1.8 on 2020-12-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0046_mailtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailTime',
        ),
    ]
