# Generated by Django 2.1.8 on 2021-01-07 08:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0048_paymentmethod_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment',
        ),
        migrations.AddField(
            model_name='ordersource',
            name='payment_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Payment Method'),
        ),
    ]
