# Generated by Django 2.1.8 on 2021-01-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0049_auto_20210107_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethod_payment', to='independent.Independent_PaymentMethods'),
        ),
    ]
