# Generated by Django 2.1.8 on 2021-01-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0050_paymentmethod_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenExpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('token_creation_time', models.DateTimeField(blank=True, null=True, verbose_name='Creation Date')),
                ('token_use_time', models.DateTimeField(blank=True, null=True, verbose_name='Token Use time')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Token Expire Manager',
                'verbose_name_plural': 'Token Expire Manager',
            },
        ),
    ]
