# Generated by Django 2.1.8 on 2021-03-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0027_auto_20210303_1234'),
        ('Configuration', '0051_tokenexpire'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile No')),
                ('rating', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rating')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='UserExperience_comppany', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'UserExperience',
                'verbose_name_plural': 'UserExperience',
            },
        ),
    ]
