# Generated by Django 2.1.8 on 2021-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0052_userexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymaster',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Symbol'),
        ),
    ]
