# Generated by Django 2.1.8 on 2021-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0053_auto_20210614_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymaster',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Currency'),
        ),
    ]
