# Generated by Django 2.1.8 on 2021-06-17 09:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0054_auto_20210614_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='product_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
