# Generated by Django 2.1.8 on 2021-06-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0037_remove_company_billing_currency'),
        ('Configuration', '0055_paymentdetails_product_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinepaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('types', models.CharField(choices=[('delivey', 'delivery'), ('pickup', 'pickup')], max_length=50, verbose_name='Type')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OnlinepaymentStatus_comppany', to='Brands.Company', verbose_name='Company')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OnlinepaymentStatus_payment', to='Configuration.PaymentMethod')),
            ],
            options={
                'verbose_name': 'OnlinepaymentStatus',
                'verbose_name_plural': '  OnlinepaymentStatus',
            },
        ),
        migrations.AlterUniqueTogether(
            name='onlinepaymentstatus',
            unique_together={('company', 'types')},
        ),
    ]
