# Generated by Django 2.1.8 on 2021-06-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0037_remove_company_billing_currency'),
        ('Configuration', '0056_auto_20210621_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onlinepaymentstatus',
            unique_together={('company', 'types', 'payment')},
        ),
    ]
