# Generated by Django 2.1.8 on 2021-06-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0057_auto_20210621_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymentstatus',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='Is Hide'),
        ),
    ]
