# Generated by Django 2.1.8 on 2021-12-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0059_auto_20210621_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
