# Generated by Django 2.1.8 on 2021-12-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0060_auto_20211213_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersource',
            name='source',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit',
        ),
    ]
