# Generated by Django 2.1.8 on 2021-12-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0061_auto_20211213_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pincode')),
                ('prefecture', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prefecture')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': '  Address',
            },
        ),
    ]
