# Generated by Django 2.1.8 on 2020-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
        ('Outlet', '0017_auto_20200519_0822'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Id'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='outletprofile',
        #     unique_together={('Company', 'priority')},
        # ),
    ]
