# Generated by Django 2.1.8 on 2020-07-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0019_auto_20200706_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='outlet_image',
            field=models.ImageField(blank=True, null=True, upload_to='outlet_image/', verbose_name='Image'),
        ),
    ]
