# Generated by Django 2.1.8 on 2020-07-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
        ('Outlet', '0020_outletprofile_outlet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100, verbose_name='Day')),
                ('active_status', models.BooleanField(default=0, verbose_name='Active Status')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OutletTiming_Company', to='Brands.Company', verbose_name='Company')),
                ('outlet', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutletTiming_outlet', to='Outlet.OutletProfile', verbose_name='Outlet Name')),
            ],
            options={
                'verbose_name': 'Outlet Timing',
                'verbose_name_plural': '   Outlet Timing',
            },
        ),
    ]
