# Generated by Django 2.1.8 on 2020-07-09 08:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0021_outlettiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlettiming',
            name='allday',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
