# Generated by Django 2.1.8 on 2020-07-10 05:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0022_outlettiming_allday'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletTimingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allday', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('outlet', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutletTimingMaster_outlet', to='Outlet.OutletProfile', verbose_name='Outlet Name')),
            ],
            options={
                'verbose_name': 'Outlet Timing',
                'verbose_name_plural': '   Outlet Timing',
            },
        ),
        migrations.AddField(
            model_name='outlettiming',
            name='masterid',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutletTiming_masterid', to='Outlet.OutletTimingMaster', verbose_name='Master ID'),
        ),
    ]
