# Generated by Django 2.1.8 on 2020-07-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_statemaster_short_name'),
        ('Brands', '0008_auto_20200717_1455'),
        ('Outlet', '0026_auto_20200717_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Outlet_country', to='Location.CountryMaster', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
        migrations.AlterField(
            model_name='outletprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.RemoveField(
            model_name='outletprofile',
            name='area',
        ),
        # migrations.AlterUniqueTogether(
        #     name='outletprofile',
        #     unique_together={('Company', 'priority')},
        # ),
    ]
