# Generated by Django 2.1.8 on 2020-08-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0010_company_is_payment'),
        ('Outlet', '0030_auto_20200725_1625'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='outletprofile',
        #     unique_together={('Company', 'priority')},
        # ),
    ]
