# Generated by Django 2.1.8 on 2020-08-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0010_company_is_payment'),
        ('Outlet', '0031_auto_20200810_1352'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
        migrations.RemoveField(
            model_name='outletprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='outletprofile',
            name='username',
        ),
        # migrations.AlterUniqueTogether(
        #     name='outletprofile',
        #     unique_together={('Company', 'priority')},
        # ),
    ]
