# Generated by Django 2.1.8 on 2020-08-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0029_auto_20200804_1614'),
        ('Brands', '0011_auto_20200817_1818'),
        ('Outlet', '0032_auto_20200817_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_temp', models.FloatField(verbose_name='Body Temp in F')),
                ('is_latest', models.BooleanField(default=1, verbose_name='Is Latest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='TempTracking_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Staff Temperature Tracking',
                'verbose_name_plural': '   Staff Temperature Tracking',
            },
        ),
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='outletprofile',
        #     unique_together={('Company', 'priority')},
        # ),
        migrations.AddField(
            model_name='temptracking',
            name='outlet',
            field=models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='TempTracking_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
        migrations.AddField(
            model_name='temptracking',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='TempTracking_staff', to='UserRole.ManagerProfile', verbose_name='Staff Mmeber'),
        ),
    ]
