# Generated by Django 2.1.8 on 2020-08-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0011_auto_20200817_1818'),
        ('Outlet', '0033_auto_20200818_1038'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
        migrations.AddField(
            model_name='outlettimingmaster',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OutletTimingMaster_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
        # migrations.AlterUniqueTogether(
        #     name='outletprofile',
        #     unique_together={('Company', 'priority')},
        # ),
    ]
