# Generated by Django 2.1.8 on 2020-08-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0011_auto_20200817_1818'),
        ('Outlet', '0034_auto_20200825_1056'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='outletprofile',
        #     unique_together={('Company', 'priority')},
        # ),
    ]
