# Generated by Django 2.1.8 on 2020-09-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0012_company_plan_name'),
        ('Outlet', '0039_auto_20200909_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlettiming',
            name='slot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slot'),
        ),

    ]
