# Generated by Django 2.1.8 on 2020-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0012_company_plan_name'),
        ('Outlet', '0047_auto_20201003_1538'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='outletprofile',
        #     unique_together={('Company', 'priority')},
        # ),
    ]
