# Generated by Django 2.1.8 on 2020-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0048_auto_20201005_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='average_delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Average Delivery Time'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='min_order_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimium Order Value'),
        ),
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
    ]
