# Generated by Django 2.1.8 on 2020-10-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0049_auto_20201008_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='outlet_instagram',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Instagram'),
        ),
        # migrations.AddField(
        #     model_name='outletprofile',
        #     name='priority',
        #     field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        # ),
    ]
