# Generated by Django 2.1.8 on 2020-10-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0050_auto_20201012_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
    ]
