# Generated by Django 2.1.8 on 2020-10-16 09:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0051_outletprofile_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='map_city',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='All City'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='map_locality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Locality'),
        ),
    ]
