# Generated by Django 2.1.8 on 2020-10-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0053_auto_20201017_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletprofile',
            name='om_pic',
        ),
    ]
