# Generated by Django 2.1.8 on 2020-10-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0008_areamaster_company'),
        ('Outlet', '0054_remove_outletprofile_om_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='no_of_days',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='No Of Days'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='state',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Outlet_state', to='Location.StateMaster', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='time_range',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Time Range'),
        ),
    ]
