# Generated by Django 2.1.8 on 2020-10-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0056_outletprofile_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Min Value'),
        ),
        migrations.AlterField(
            model_name='outletprofile',
            name='min_order_value',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Minimium Order Value'),
        ),
    ]
