# Generated by Django 2.1.8 on 2020-10-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0057_auto_20201020_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletprofile',
            name='min_order_value',
        ),
    ]
