# Generated by Django 2.1.8 on 2020-10-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0058_remove_outletprofile_min_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
