# Generated by Django 2.1.8 on 2020-12-04 08:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0059_auto_20201023_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletprofile',
            name='outlet_instagram',
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='payment_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='payment_method'),
        ),
    ]
