# Generated by Django 2.1.8 on 2021-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0063_auto_20210421_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='is_hide',
            field=models.BooleanField(default=0, verbose_name='Is Hide'),
        ),
    ]
