# Generated by Django 2.1.8 on 2021-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0064_outletprofile_is_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='clean_kitchen',
            field=models.BooleanField(default=0, verbose_name='Is clean_kitchen'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='sanitized_restaurant',
            field=models.BooleanField(default=0, verbose_name='Is sanitized_restaurant'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='temperature_check',
            field=models.BooleanField(default=0, verbose_name='Is temperature_check'),
        ),
    ]
