# Generated by Django 2.1.8 on 2021-06-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0065_auto_20210616_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='min_delivery_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Delivery Time'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='min_picking_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Picking Time'),
        ),
    ]
