# Generated by Django 2.1.8 on 2021-06-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0066_auto_20210628_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='outlet_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outlet Email'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='outlet_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outlet Phone'),
        ),
    ]
