# Generated by Django 2.1.8 on 2021-07-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0041_linkedaccount_routetrack'),
        ('Outlet', '0067_auto_20210628_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_slot_1_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Opening Time for Monday')),
                ('monday_slot_1_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Closing Time for Monday')),
                ('monday_slot_2_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Opening Time for Monday')),
                ('monday_slot_2_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Closing Time for Monday')),
                ('tuesday_slot_1_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Opening Time for Tuesday')),
                ('tuesday_slot_1_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Closing Time for Tuesday')),
                ('tuesday_slot_2_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Opening Time for Tuesday')),
                ('tuesday_slot_2_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Closing Time for Tuesday')),
                ('wednesday_slot_1_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Opening Time for Wednesday')),
                ('wednesday_slot_1_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Closing Time for Wednesday')),
                ('wednesday_slot_2_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Opening Time for Wednesday')),
                ('wednesday_slot_2_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Closing Time for Wednesday')),
                ('thursday_slot_1_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Opening Time for Thursday')),
                ('thursday_slot_1_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Closing Time for Thursday')),
                ('thursday_slot_2_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Opening Time for Thursday')),
                ('thursday_slot_2_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Closing Time for Thursday')),
                ('friday_slot_1_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Opening Time for Friday')),
                ('friday_slot_1_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Closing Time for Friday')),
                ('friday_slot_2_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Opening Time for Friday')),
                ('friday_slot_2_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Closing Time for Friday')),
                ('saturday_slot_1_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Opening Time for Saturday')),
                ('saturday_slot_1_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Closing Time for Saturday')),
                ('saturday_slot_2_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Opening Time for Saturday')),
                ('saturday_slot_2_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Closing Time for Saturday')),
                ('sunday_slot_1_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Opening Time for Sunday')),
                ('sunday_slot_1_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 1 Closing Time for Sunday')),
                ('sunday_slot_2_opening', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Opening Time for Sunday')),
                ('sunday_slot_2_closing', models.TimeField(blank=True, null=True, verbose_name='Slot 2 Closing Time for Sunday')),
                ('is_closed_1', models.BooleanField(default=0, verbose_name='Closed on Day 1')),
                ('is_closed_2', models.BooleanField(default=0, verbose_name='Closed on Day 2')),
                ('is_closed_3', models.BooleanField(default=0, verbose_name='Closed on Day 3')),
                ('is_closed_4', models.BooleanField(default=0, verbose_name='Closed on Day 4')),
                ('is_closed_5', models.BooleanField(default=0, verbose_name='Closed on Day 5')),
                ('is_closed_6', models.BooleanField(default=0, verbose_name='Closed on Day 6')),
                ('is_closed_7', models.BooleanField(default=0, verbose_name='Closed on Day 7')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Outlet TimeTable',
                'verbose_name_plural': 'Outlet TimeTable',
            },
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='aggre_store_action_ref_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Swiggy Store Action Ref ID'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='is_synced',
            field=models.BooleanField(default=0, verbose_name='Is Synced'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='swiggy_open_status',
            field=models.BooleanField(default=1, verbose_name='Is Swiggy Open'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='sync_request_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sync Request Id'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='sync_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('not_intiated', 'Not Initiated'), ('in_progress', 'In Progress'), ('synced', 'Synced')], default='not_applicable', max_length=50, verbose_name='Sync Status'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='urban_event',
            field=models.CharField(blank=True, choices=[('updated', 'Store Updated'), ('created', 'Store Created')], max_length=50, null=True, verbose_name='Event At UrbanPiper'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='urbanpiper_store_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UrbanPiper Store Id'),
        ),
        migrations.AddField(
            model_name='outletprofile',
            name='zomato_open_status',
            field=models.BooleanField(default=1, verbose_name='Is Zomato Open'),
        ),
        migrations.AddField(
            model_name='outlettimetable',
            name='outlet',
            field=models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
    ]
