# Generated by Django 2.1.8 on 2022-02-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0072_auto_20220128_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP Address'),
        ),
    ]
