# Generated by Django 2.1.8 on 2020-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Twitter'),
        ),
    ]
