# Generated by Django 2.1.8 on 2020-07-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0008_auto_20200717_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_city', to='Location.CityMaster', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email_id',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Contact Email Id'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_registrationNo',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Company Registration No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Person Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person_email_id',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Contact Other Email ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person_landlineno',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Landline No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person_mobileno',
            field=models.CharField(blank=True, help_text='Please enter Country /ISD code before mobile number', max_length=15, null=True, verbose_name='Contact Mobile No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_country', to='Location.CountryMaster', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_open',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Is Open'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Owner Email Id'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Please enter Country /ISD code before mobile number', max_length=15, null=True, verbose_name='Owner Mobile No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_state', to='Location.StateMaster', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='support_person_email_id',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Support Email ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='support_person_landlineno',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Support Landline No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='support_person_mobileno',
            field=models.CharField(blank=True, help_text='Please enter Country /ISD code before mobile number', max_length=15, null=True, verbose_name='Support Mobile No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN Code'),
        ),
    ]
