# Generated by Django 2.1.8 on 2020-08-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0009_auto_20200720_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_payment',
            field=models.BooleanField(default=0, verbose_name='Is Payment'),
        ),
    ]
