# Generated by Django 2.1.8 on 2020-08-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0001_initial'),
        ('Brands', '0011_auto_20200817_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan_name',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_plan_name', to='Subscription.SubscriptionPlanType', verbose_name='Plan Name'),
            preserve_default=False,
        ),
    ]
