# Generated by Django 2.1.8 on 2020-09-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0012_company_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subdomain',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Brand Subdomain'),
        ),
    ]
