# Generated by Django 2.1.8 on 2020-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0014_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(default=1, max_length=35, verbose_name='Template'),
            preserve_default=False,
        ),
    ]
