# Generated by Django 2.1.8 on 2020-11-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0016_homepage_homepagepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='home'),
        ),
    ]
