# Generated by Django 2.1.8 on 2020-11-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0017_homepage_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hello_image_mobile',
            new_name='mobile_slider',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hello_image_web',
            new_name='web_slider',
        ),
    ]
