# Generated by Django 2.1.8 on 2020-11-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0019_auto_20201109_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='promotions_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Promotions Url'),
        ),
    ]
