# Generated by Django 2.1.8 on 2020-11-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0020_homepage_promotions_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_locality',
            field=models.BooleanField(default=0, verbose_name='Has Locality'),
        ),
    ]
