# Generated by Django 2.1.8 on 2020-11-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0021_company_has_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='MenuCount_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Menu Count',
                'verbose_name_plural': '          Menu Count',
            },
        ),
    ]
