# Generated by Django 2.1.8 on 2020-11-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0022_menucount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucount',
            name='company',
        ),
        migrations.DeleteModel(
            name='MenuCount',
        ),
    ]
