# Generated by Django 2.1.8 on 2020-11-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0023_auto_20201111_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Page_page', to='independent.Independent_Page'),
        ),
    ]
