# Generated by Django 2.1.8 on 2020-12-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0024_page_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attendance_type',
            field=models.CharField(blank=True, choices=[('one_time', 'One Time'), ('multiple_time', 'Multiple Time')], max_length=50, null=True, verbose_name='Attendance Type'),
        ),
    ]
