# Generated by Django 2.1.8 on 2021-01-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0025_company_attendance_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': '  Homepage'},
        ),
    ]
