# Generated by Django 2.1.8 on 2021-03-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0026_auto_20210118_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagepromotion',
            options={'verbose_name': 'Homepage Promotions', 'verbose_name_plural': '  Homepage Promotions'},
        ),
    ]
