# Generated by Django 2.1.8 on 2021-04-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0027_auto_20210303_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email_id',
            field=models.EmailField(default=1, max_length=50, unique=True, verbose_name='Contact Email Id'),
            preserve_default=False,
        ),
    ]
