# Generated by Django 2.1.8 on 2021-04-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0028_auto_20210420_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_firstUser',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='is_firstUser'),
        ),
    ]
