# Generated by Django 2.1.8 on 2021-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0029_company_is_firstuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='login_type',
            field=models.CharField(choices=[('plain', 'plain'), ('google', 'google')], default='plain', max_length=50, verbose_name='Login Type'),
        ),
    ]
