# Generated by Django 2.1.8 on 2021-05-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0030_company_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Brand Name'),
        ),
    ]
