# Generated by Django 2.1.8 on 2021-06-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0031_auto_20210512_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('company', models.ManyToManyField(to='Brands.Company')),
            ],
            options={
                'verbose_name': '    Merge Brand',
                'verbose_name_plural': '    Merge Brand',
            },
        ),
    ]
