# Generated by Django 2.1.8 on 2021-06-15 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0032_mergebrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OutOfRange_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '    Out Of Range',
                'verbose_name_plural': '    Out Of Range',
            },
        ),
    ]
