# Generated by Django 3.1.4 on 2021-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0032_mergebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
