# Generated by Django 3.1.4 on 2021-06-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0033_company_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='eion_outlet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
