# Generated by Django 2.1.8 on 2021-06-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0033_outofrange'),
        ('Brands', '0033_company_api_key'),
    ]

    operations = [
    ]
