# Generated by Django 2.1.8 on 2021-06-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0034_merge_20210617_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='billing_currency',
        ),
    ]
