# Generated by Django 3.1.4 on 2021-06-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0034_company_eion_outlet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='eion_outlet_id',
            new_name='eion_brand_id',
        ),
    ]
