# Generated by Django 2.1.8 on 2021-06-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0054_auto_20210614_1803'),
        ('Brands', '0035_remove_company_billing_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_currency',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_billing_currency', to='Configuration.CurrencyMaster', verbose_name='Billing Currency'),
        ),
    ]
