# Generated by Django 2.1.8 on 2021-06-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0037_remove_company_billing_currency'),
        ('Brands', '0034_company_eion_outlet_id'),
    ]

    operations = [
    ]
