# Generated by Django 2.1.8 on 2021-06-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0035_auto_20210625_1318'),
        ('Brands', '0038_merge_20210622_1522'),
    ]

    operations = [
    ]
