# Generated by Django 2.1.8 on 2021-06-26 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0065_auto_20210616_1254'),
        ('Customers', '0010_customerprofile_is_google'),
        ('Product', '0081_auto_20210626_1115'),
        ('Brands', '0039_merge_20210625_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rating')),
                ('review', models.CharField(blank=True, max_length=400, null=True, verbose_name='Review')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('is_approve', models.BooleanField(default=0, verbose_name='Is Approve')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewmaster_comppany', to='Brands.Company', verbose_name='Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_customer', to='Customers.CustomerProfile', verbose_name='Customer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_outlet', to='Outlet.OutletProfile', verbose_name='Company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_product', to='Product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'ReviewMaster',
                'verbose_name_plural': 'ReviewMaster',
            },
        ),
    ]
