# Generated by Django 2.1.8 on 2021-06-27 08:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0059_auto_20210621_1509'),
        ('Brands', '0040_reviewmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Name_Rzp', models.CharField(blank=True, max_length=500, null=True)),
                ('Account_Email', models.CharField(blank=True, max_length=500, null=True)),
                ('BranchIFSC_Code', models.CharField(blank=True, max_length=500, null=True)),
                ('Account_Number', models.CharField(blank=True, max_length=500, null=True)),
                ('Beneficiary_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('acc_id', models.CharField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('isStartedUsingEion', models.BooleanField(default=0)),
                ('active_status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='brand_linked_accs', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Linked Account',
                'verbose_name_plural': 'Linked Accounts',
            },
        ),
        migrations.CreateModel(
            name='RouteTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Processed', 'Processed'), ('Scheduled', 'Scheduled')], max_length=200, null=True)),
                ('rzp_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('transfer_rzp_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('Order_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('transfer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Payment_link_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_details', models.CharField(blank=True, max_length=2000, null=True)),
                ('brand', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='brand_route_accs', to='Brands.Company', verbose_name='Company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_cuurency', to='Configuration.CurrencyMaster')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
