# Generated by Django 2.1.8 on 2021-12-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0041_linkedaccount_routetrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page',
        ),
    ]
