# Generated by Django 2.1.8 on 2020-07-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0039_auto_20200515_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='Image')),
                ('primary_image', models.BooleanField(default=1, verbose_name='Primary Image')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('product', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ProductImage_product', to='Product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': '          Product Image',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='subcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_image/', verbose_name='Image'),
        ),
    ]
