# Generated by Django 2.1.8 on 2020-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0041_auto_20200708_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergen_Information',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='allergen_Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='spice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Spice'),
        ),
    ]
