# Generated by Django 2.1.8 on 2020-07-17 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0042_auto_20200717_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergen_Information',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Allergen Information'),
        ),
    ]
