# Generated by Django 2.1.8 on 2020-07-31 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0043_auto_20200717_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='product_categorys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Product_Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategorys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='product_subcategory'),
        ),
    ]
