# Generated by Django 2.1.8 on 2020-08-05 07:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0016_primaryingredient_unit'),
        ('Product', '0044_auto_20200731_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primaryIngredient_deatils',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_ingredient',
            field=models.ForeignKey(default=10, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, to='kitchen.SecondaryIngredient', verbose_name='SecondaryIngredient'),
            preserve_default=False,
        ),
    ]
