# Generated by Django 2.1.8 on 2020-08-06 06:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0046_auto_20200805_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_categorys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcategorys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
