# Generated by Django 2.1.8 on 2020-08-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0012_company_plan_name'),
        ('Product', '0048_auto_20200828_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Productsubcategory_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
