# Generated by Django 2.1.8 on 2020-09-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0049_productsubcategory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.FoodType', verbose_name='Product Type'),
        ),
    ]
