# Generated by Django 2.1.8 on 2020-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0052_auto_20200909_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spice'),
        ),
    ]
