# Generated by Django 2.1.8 on 2020-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0054_product_product_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_charge',
            field=models.FloatField(blank=True, null=True, verbose_name='Packing Charge'),
        ),
    ]
