# Generated by Django 2.1.8 on 2020-10-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0013_company_subdomain'),
        ('Product', '0056_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Menu_Company', to='Brands.Company', verbose_name='Company'),
        ),
    ]
