# Generated by Django 2.1.8 on 2020-10-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0057_menu_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.FileField(blank=True, null=True, upload_to='menu_image/', verbose_name='Image'),
        ),
    ]
