# Generated by Django 2.1.8 on 2020-10-21 09:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0060_product_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_option',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
