# Generated by Django 2.1.8 on 2020-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0061_product_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='barcode_pic',
            field=models.CharField(default=1, max_length=100, verbose_name='Barcode Pic'),
            preserve_default=False,
        ),
    ]
