# Generated by Django 2.1.8 on 2020-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0062_menu_barcode_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='barcode_pic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode Pic'),
        ),
    ]
