# Generated by Django 2.1.8 on 2020-10-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0063_auto_20201030_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='barcode_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode Info'),
        ),
    ]
