# Generated by Django 2.1.8 on 2020-11-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0065_menu_base_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='base_code',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='base code'),
        ),
    ]
