# Generated by Django 2.1.8 on 2020-11-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0023_auto_20201111_1646'),
        ('Product', '0066_auto_20201102_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, verbose_name='Menu Name')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='MenuCount_Company', to='Brands.Company', verbose_name='Company')),
                ('menu', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='MenuCount_menu', to='Product.Menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Menu Count',
                'verbose_name_plural': '          Menu Count',
            },
        ),
    ]
