# Generated by Django 2.1.8 on 2020-11-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0067_menucount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='menucount',
            name='menu',
        ),
        migrations.DeleteModel(
            name='MenuCount',
        ),
    ]
