# Generated by Django 2.1.8 on 2021-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0070_auto_20201202_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addons',
            options={'verbose_name': 'Add-on', 'verbose_name_plural': '  Add-ons'},
        ),
        migrations.AlterModelOptions(
            name='featureproduct',
            options={'verbose_name': 'Feature', 'verbose_name_plural': ' Feature Product'},
        ),
        migrations.AlterModelOptions(
            name='foodtype',
            options={'verbose_name': 'Food Type', 'verbose_name_plural': ' Food Type'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': '  Menu'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Variant', 'verbose_name_plural': ' Variants'},
        ),
        migrations.AddField(
            model_name='product',
            name='packing_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Package Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Price Type'),
        ),
    ]
