# Generated by Django 2.1.8 on 2021-01-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0072_product_package_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_tax',
            field=models.BooleanField(default=1, verbose_name='Is Tax'),
        ),
    ]
