# Generated by Django 2.1.8 on 2021-03-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0073_product_is_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='video_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Price Type'),
        ),
    ]
