# Generated by Django 2.1.8 on 2021-05-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0074_productimage_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_subcategory', to='Product.ProductCategory', verbose_name='Category Name'),
        ),
    ]
