# Generated by Django 2.1.8 on 2021-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0075_auto_20210522_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hide',
            field=models.BooleanField(default=0, verbose_name='Is Hide'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_hide',
            field=models.BooleanField(default=0, verbose_name='Is Hide'),
        ),
    ]
