# Generated by Django 2.1.8 on 2021-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0076_auto_20210611_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='is_hide',
            field=models.BooleanField(default=0, verbose_name='Is Hide'),
        ),
    ]
