# Generated by Django 2.1.8 on 2021-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0078_menu_is_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Review'),
        ),
    ]
