# Generated by Django 2.1.8 on 2021-06-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0079_auto_20210625_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Video Url'),
        ),
    ]
