# Generated by Django 2.1.8 on 2021-11-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0081_auto_20210626_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='is_hide',
            field=models.BooleanField(default=0, verbose_name='Is Hide'),
        ),
    ]
