# Generated by Django 2.1.8 on 2022-01-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0082_addons_is_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addondetails',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='addons',
            name='addon_group',
        ),
        migrations.RemoveField(
            model_name='addons',
            name='identifier',
        ),
    ]
