# Generated by Django 2.1.8 on 2022-01-11 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0085_auto_20220111_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addondetails',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='addondetails',
            name='associated_addons',
        ),
        migrations.RemoveField(
            model_name='addondetails',
            name='priority',
        ),
        migrations.AddField(
            model_name='addondetails',
            name='addons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Addons'),
        ),
    ]
