# Generated by Django 2.1.8 on 2022-01-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0086_auto_20220111_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordering_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ordering Code'),
        ),
    ]
