# Generated by Django 2.1.8 on 2020-08-27 07:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Configuration', '0023_ordersource_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=30, verbose_name='Subscription Type')),
                ('membership_status', models.CharField(blank=True, choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], max_length=20, null=True, verbose_name='Plan Type')),
                ('cost', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Amount')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_currency', to='Configuration.CurrencyMaster', verbose_name='Currency')),
            ],
            options={
                'verbose_name': '   Subscription Plan',
                'verbose_name_plural': '   Subscription Plan',
            },
        ),
    ]
