# Generated by Django 2.1.8 on 2021-05-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0031_auto_20210512_2220'),
        ('Subscription', '0002_subscriptionpaymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatewaypayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('receipt_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Razorpay Receipt Id')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Razorpay Payment Id')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Razorpay Order Id')),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Razorpay Signature')),
                ('amount', models.FloatField(blank=True, max_length=35, null=True, verbose_name='Amount')),
                ('is_successful', models.BooleanField(default=0, verbose_name='Is Successful')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brands.Company', verbose_name='Company payments')),
            ],
            options={
                'verbose_name': ' Customer Razorpay Payment History',
                'verbose_name_plural': 'Customer Razorpay Payment History',
            },
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='isRecommended',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='is_custom_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='is_customer_segmentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='is_eion_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='is_support_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='is_video_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='is_zone_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='orders_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='outlet_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='product_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='subscriptionplantype',
            name='user_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
