# Generated by Django 2.1.8 on 2021-03-03 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0027_auto_20210303_1234'),
        ('Notification', '0003_auto_20210302_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverify',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='EmailVerify_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
