# Generated by Django 2.1.8 on 2021-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0004_emailverify_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
