# Generated by Django 2.1.8 on 2021-04-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0007_emailverify_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='Company',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmailVerify_Company', to='Brands.Company', verbose_name='Company'),
        ),
    ]
