# Generated by Django 2.1.8 on 2021-06-03 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0009_notificationcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcard',
            name='outlet',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='outlet'),
        ),
        migrations.AlterField(
            model_name='notificationcard',
            name='active_status',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
