# Generated by Django 2.1.8 on 2021-01-04 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0019_auto_20200327_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='flat_discount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Flat Discount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='flat_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Percentage Discount'),
        ),
    ]
