# Generated by Django 2.1.8 on 2021-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0021_auto_20210104_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='flat_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Flat Discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='flat_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Discount'),
        ),
    ]
