# Generated by Django 2.1.8 on 2021-01-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0022_auto_20210104_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='flat_discount',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Flat Discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='flat_percentage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Percentage Discount'),
        ),
    ]
