# Generated by Django 2.1.8 on 2021-06-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0024_auto_20210104_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discount_image/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_banner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Banner'),
        ),
        migrations.AddField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discount_image/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_banner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Banner'),
        ),
    ]
