# Generated by Django 2.1.8 on 2021-06-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0025_auto_20210607_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_image/', verbose_name='Image'),
        ),
    ]
