# Generated by Django 2.1.8 on 2020-08-04 10:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0028_managerprofile_login_type'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='managerprofile',
        #     name='login_type',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Login Type'),
        # ),
    ]
