# Generated by Django 2.1.8 on 2020-10-24 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0013_company_subdomain'),
        ('UserRole', '0030_auto_20200825_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff Name')),
                ('in_time', models.DateTimeField(blank=True, null=True, verbose_name='In Time')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='Out Time')),
                ('temp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff Name')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Attendance_Company', to='Brands.Company', verbose_name='Company')),
                ('profile', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Attendance', to='UserRole.ManagerProfile', verbose_name='Staff')),
            ],
            options={
                'verbose_name': '    name',
                'verbose_name_plural': '    name',
            },
        ),
    ]
