# Generated by Django 2.1.8 on 2020-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0032_attendance_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='In Time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Out Time'),
        ),
    ]
