# Generated by Django 2.1.8 on 2020-10-24 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0033_auto_20201024_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attendance_auth_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
