# Generated by Django 2.1.8 on 2020-10-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0034_auto_20201024_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='is_attandance',
            field=models.BooleanField(default=0, verbose_name='Is Attandance'),
        ),
    ]
