# Generated by Django 2.1.8 on 2020-10-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0035_managerprofile_is_attandance'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='employee_id',
            field=models.CharField(default=1, max_length=100, verbose_name='Employee ID'),
            preserve_default=False,
        ),
    ]
