# Generated by Django 2.1.8 on 2020-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0036_managerprofile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee ID'),
        ),
    ]
