# Generated by Django 2.1.8 on 2020-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0037_auto_20201031_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time In'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Out'),
        ),
    ]
