# Generated by Django 2.1.8 on 2020-11-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0038_auto_20201031_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
    ]
