# Generated by Django 2.1.8 on 2020-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0039_auto_20201103_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_billprint',
            field=models.BooleanField(default=0, verbose_name='Is Bill print'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status'),
        ),
    ]
