# Generated by Django 2.1.8 on 2020-12-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0040_auto_20201103_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='is_rider',
            field=models.BooleanField(default=0, verbose_name='Is Rider'),
        ),
    ]
