# Generated by Django 2.1.8 on 2020-12-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0041_managerprofile_is_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='is_assign',
            field=models.BooleanField(default=0, verbose_name='Is Rider'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
    ]
