# Generated by Django 2.1.8 on 2020-12-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0042_auto_20201222_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='compensation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='compensation'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='km',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kiolmeter'),
        ),
    ]
