# Generated by Django 2.1.8 on 2021-01-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0044_auto_20210118_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrollpermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BillRollPermission_Company', to='Brands.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='rollpermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RollPermission_Company', to='Brands.Company', verbose_name='Company'),
        ),
    ]
