# Generated by Django 2.1.8 on 2021-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0045_auto_20210122_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last Name'),
        ),
    ]
