# Generated by Django 2.1.8 on 2021-04-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0046_auto_20210421_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='is_firstUser',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='is_firstUser'),
        ),
    ]
