# Generated by Django 2.1.8 on 2020-09-22 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Outlet', '0045_auto_20200921_1709'),
        ('Brands', '0012_company_plan_name'),
        ('History', '0007_outletlogs_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event Name')),
                ('event_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event Name')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('count', models.PositiveIntegerField(blank=True, null=True, verbose_name='count')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Logs_Company', to='Brands.Company', verbose_name='Company')),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logs_auth_user', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Logs_outlet', to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'Logs',
                'verbose_name_plural': '  Logs',
            },
        ),
    ]
