# Generated by Django 2.1.8 on 2020-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0008_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order ID'),
        ),
    ]
