# Generated by Django 2.1.8 on 2020-09-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0009_logs_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='outlet',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logs_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
    ]
