# Generated by Django 2.1.8 on 2020-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0010_auto_20200922_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='relevance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relevance'),
        ),
    ]
