# Generated by Django 2.1.8 on 2020-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0012_logs_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason'),
        ),
    ]
