# Generated by Django 2.1.8 on 2020-10-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_eventtag'),
        ('History', '0013_logs_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logs_trigger', to='Event.PrimaryEventType', verbose_name='Trigger ID'),
        ),
    ]
