# Generated by Django 2.1.8 on 2020-12-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0015_menucounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderhistory',
            name='Rider',
            field=models.ForeignKey(limit_choices_to={'active_status': '1', 'is_rider': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='RiderHistory_Rider', to='UserRole.ManagerProfile', verbose_name='Rider'),
        ),
    ]
