# Generated by Django 2.1.8 on 2021-01-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0016_auto_20201222_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucounts',
            options={'verbose_name': 'Menu Count', 'verbose_name_plural': '  Menu Count'},
        ),
    ]
