# Generated by Django 2.1.8 on 2020-07-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_customerprofile_address1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='locality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='locality'),
        ),
    ]
