# Generated by Django 2.1.8 on 2021-05-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_customerprofile_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(max_length=100, verbose_name='User Name'),
        ),
    ]
