# Generated by Django 2.1.8 on 2021-06-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_auto_20210528_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_google',
            field=models.BooleanField(default=0, verbose_name='Is Google'),
        ),
    ]
