# Generated by Django 2.1.8 on 2020-07-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0013_primaryingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Ingredient', verbose_name='Ingredient Image'),
        ),
    ]
