# Generated by Django 2.1.8 on 2020-07-30 07:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0015_secondaryingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryingredient',
            name='unit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Mapped Unit Ids'),
        ),
    ]
