# Generated by Django 2.1.8 on 2020-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0018_secondaryingredient_primary_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='PrimaryIngredient name'),
        ),
    ]
