# Generated by Django 2.1.8 on 2020-10-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0019_auto_20201027_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='PrimaryIngredient name'),
        ),
    ]
