# Generated by Django 2.1.8 on 2020-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0020_auto_20201027_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryingredient',
            name='is_receipe',
            field=models.BooleanField(default=True, verbose_name='Is Recommended'),
        ),
    ]
