# Generated by Django 2.1.8 on 2020-11-09 08:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0021_primaryingredient_is_receipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryingredient',
            name='output_yield',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
