# Generated by Django 2.1.8 on 2020-11-10 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0022_secondaryingredient_output_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryingredient',
            name='unit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Mapped Unit Ids'),
        ),
    ]
