# Generated by Django 2.1.8 on 2020-11-11 03:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0066_auto_20201102_1526'),
        ('Brands', '0021_company_has_locality'),
        ('kitchen', '0023_secondaryingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_type', models.CharField(blank=True, choices=[('primary', 'Primary Ingredient'), ('secondary', 'Secondary Ingredient')], max_length=50, null=True, verbose_name='Ingredient Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Ingredient', verbose_name='Ingredient Image')),
                ('primary_deatils', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='RecipeIngredient_Company', to='Brands.Company', verbose_name='Company')),
                ('food_type', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReceipeIngredient_food', to='Product.FoodType', verbose_name='Food Type')),
            ],
            options={
                'verbose_name': 'Receipe',
                'verbose_name_plural': ' Receipe',
            },
        ),
    ]
