# Generated by Django 2.1.8 on 2020-11-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0024_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Ingredient name'),
            preserve_default=False,
        ),
    ]
