# Generated by Django 2.1.8 on 2020-11-11 03:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0025_recipeingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='output_yield',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
