# Generated by Django 2.1.8 on 2020-08-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0040_order_distance'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='order',
        #     name='order_source',
        #     field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Configuration.OrderSource', verbose_name='Order Source'),
        # ),
        # migrations.AlterField(
        #     model_name='order',
        #     name='payment_mode',
        #     field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Payment mode'),
        # ),
    ]
