# Generated by Django 2.1.8 on 2020-09-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0043_order_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='delivery_instructions'),
        ),
    ]
