# Generated by Django 2.1.8 on 2020-09-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0046_auto_20200915_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_delivery_time',
            new_name='schedule_delivery_time',
        ),
    ]
