# Generated by Django 2.1.8 on 2020-12-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0047_auto_20200915_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_rider': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserRole.ManagerProfile', verbose_name='Delivery Boy'),
        ),
    ]
