# Generated by Django 2.1.8 on 2021-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0049_order_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='schedule_time',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='schedule_time'),
        ),
    ]
