# Generated by Django 2.1.8 on 2020-11-06 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserRole', '0040_auto_20201103_1623'),
        ('Brands', '0013_company_subdomain'),
        ('Outlet', '0059_auto_20201023_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff Member Name')),
                ('time_in', models.DateTimeField(blank=True, null=True, verbose_name='Time In')),
                ('time_out', models.DateTimeField(blank=True, null=True, verbose_name='Time Out')),
                ('status', models.CharField(blank=True, choices=[('present', 'Present'), ('lwp', 'Leave without pay'), ('cl', 'Casual leave'), ('el', 'Earned leave'), ('weeklyoff', 'Weekly Off')], max_length=50, null=True, verbose_name='Status')),
                ('is_billprint', models.BooleanField(default=0, verbose_name='Is Bill print')),
                ('temperature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff Name')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_attendance', to='Brands.Company', verbose_name='Company')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_attendance', to='Outlet.OutletProfile')),
                ('profile', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='UserRole.ManagerProfile', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance',
            },
        ),
    ]
