# Generated by Django 2.1.8 on 2020-12-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20201106_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(blank=True, null=True, verbose_name='Time In')),
                ('time_out', models.DateTimeField(blank=True, null=True, verbose_name='Time Out')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttendanceTime_attendance_id', to='attendance.StaffAttendance', verbose_name='attendance_id')),
            ],
            options={
                'verbose_name': 'Staff AttendanceTime',
                'verbose_name_plural': 'Staff AttendanceTime',
            },
        ),
    ]
