# Generated by Django 2.1.8 on 2020-12-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetime',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('lwp', 'Leave without pay'), ('cl', 'Casual leave'), ('el', 'Earned leave'), ('weeklyoff', 'Weekly Off')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
